config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "posts#index"
  get '/posts/category/:id', to: "posts#category"
  resources :posts do
    resources :comments, only: [:create, :destroy]
    get :search, on: :collection
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'お肉のおかず' },
    { id: 3, name: '魚介のおかず' },
    { id: 4, name: '野菜のおかず' },
    { id: 5, name: 'ご飯もの' },
    { id: 6, name: '卵料理' },
    { id: 7, name: 'パスタ・グラタン' },
    { id: 8, name: '麺類' },
    { id: 9, name: '副菜・サラダ' },
    { id: 10, name: 'スープ・汁物・シチュー' },
    { id: 11, name: 'お菓子・スイーツ' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

  validates :category_id, numericality: { other_than: 1 }

  def self.search(search)
    if search
      Post.where(['title LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post, dependent: :destroy

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to "/posts/#{@comment.post.id}"
    else
      @post = Post.find(@comment.post.id)
      @comments = @post.comments.includes(:user)
      render 'posts/show'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    comment = @post.comments.find(params[:id])
    if current_user.id == comment.user_id
      comment.destroy
      redirect_to post_path(params[:post_id])
    else
      render 'posts/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(params[:id])
    else
      @post = Post.find(params[:id])
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def category
    @post = Post.find_by(category_id: params[:id])
    @posts = Post.where(category_id: params[:id]).order('created_at DESC')
  end

  def search
    # Viewのformで取得したパラメータをモデルに渡す
    @posts = Post.search(params[:search])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :category_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("8.png", class: :logo), root_path %>
          </div>

              <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

              <%= form_tag(search_posts_path,:method => 'get',class: :search_form) do %>
                <%= text_field_tag :search %>
                <%= submit_tag '検索', :name => nil, class: :search_btn %>
              <% end %>
              
              <div class="nav__logout" id="lists">カテゴリで探す</div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "新規投稿", new_post_path, class: :nav__btn %>
              <%= link_to "#{current_user.name}", user_path(current_user.id), class: :nav__name %>
            </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
          
        </div>
        
      </div>

    </header>

    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Recire blog All rights reserved.</p>
    </footer>
  </body>
</html>


 <ul class="show-lists hidden" id="pull-down">
        <li class="pull-down-list" id="pull-lists"><%= link_to 'お肉のおかず', '/posts/category/2' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to '魚介のおかず', '/posts/category/3' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to '野菜のおかず', '/posts/category/4' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to 'ご飯もの', '/posts/category/5' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to '卵料理', '/posts/category/6' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to 'パスタ・グラタン', '/posts/category/7' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to '麺類', '/posts/category/8' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to '副菜・サラダ', '/posts/category/9' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to '汁物・シチュー', '/posts/category/10' %></li>
        <li class="pull-down-list" id="pull-lists"><%= link_to 'お菓子・スイーツ', '/posts/category/11' %></li>
      </ul>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f|%>
<%= render partial: 'errors/error_messages', locals: {model: post}%> 
  <div class="field">
    <%= f.label :category, "カテゴリ" %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>

  <div class="field">
    <%= f.label :tite, "タイトル" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :body, "内容" %><br />
    <%= f.text_area :body, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
    <div id="image-list"></div>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <p class="tag"><%= post.category.name %></p>
  <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id) %>
  <div class="card__body">
    <%= link_to post.title, post_path(post.id), class: :card__title%>

  <%# いいね部分始まり %>
  <div class="like_group">
    <p class= "heart-icon">
      <i class="fas fa-heart"></i>
    </p>
    <p class="post-count-number">
      <%=post.liked_users.count %>
    </p>
  </div>
  <%# いいね部分終わり %>
    <div class ="post-bottom">
      <p class="created"><%= l post.created_at,format: :short %></p>
      <%= link_to "by #{post.user.name}", user_path(post.user_id), class: :card__user %>
    </div>
  </div>
</div>

app/views/posts/category.html.erb
<% if @post != nil %>
    <div class="category_card">
      <div class= "category_title">
        <%= @post.category.name %>   の投稿一覧
      </div>
      <div class="category_parent">
        <% @posts.each do |post| %>
          <div class="category_child">
            <p class="tag"><%= post.category.name %></p>
            <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id) %>
            <div class="card__body">
              <%= link_to post.title, post_path(post.id), class: :card__title%>

                <%# いいね部分始まり %>
                <div class="like_group">
                  <p class= "heart-icon">
                    <i class="fas fa-heart"></i>
                  </p>
                  <p class="post-count-number">
                    <%=post.liked_users.count %>
                  </p>
                </div>
                <%# いいね部分終わり %>
                 <div class ="post-bottom">
                  <p class="created"><%= l post.created_at,format: :short %></p>
                  <%= link_to "by #{post.user.name}", user_path(post.user_id), class: :card__user %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
      <button type="button" class="btn btn-outline-primary">
        <%= link_to "ホームへ戻る", root_path %>
      </button>
    </div>
<% else %>
    <div class="no_category_card">
      <div class="no_category">
        投稿はありません。 
      </div>
        <div class="home_btn">
          <button type="button" class="btn btn-outline-primary">
            <%= link_to "ホームへ戻る", root_path %>
          </button>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">編集</h2>
        <%= render partial: "form" ,locals: {post: @post}%>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
       <div class="greeting"> 
         <p>こんにちは、<%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link %> </p>
      </div> 
    <% end %>
    <div class="card__wrapper">
        <%= render partial: "post", collection: @posts %>
    </div>

  </div>
</main>

app/views/posts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規レシピ投稿</h2>
        <%= render partial: "form" ,locals: {post: @post}%>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="category_card">
  <div class="category_parent">
    <% @posts.each do |post| %>
      <div class="category_child">
        <p class="tag"><%= post.category.name %></p>
        <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id) %>
        <div class="card__body">
          <%= link_to post.title, post_path(post.id), class: :card__title%>
            <%# いいね部分始まり %>
            <div class="like_group">
              <p class= "heart-icon">
                <i class="fas fa-heart"></i>
              </p>
              <p class="post-count-number">
                <%=post.liked_users.count %>
              </p>
            </div>
            <%# いいね部分終わり %>
            <div class ="post-bottom">
              <p class="created"><%= l post.created_at,format: :short %></p>
              <%= link_to "by #{post.user.name}", user_path(post.user_id), class: :card__user %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
  <button type="button" class="btn btn-outline-primary">
    <%= link_to "ホームへ戻る", root_path %>
  </button>
</div>

app/views/posts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @post.title%>
      </p>
      <%= link_to "by #{@post.user.name}", user_path(@post.user_id), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_post_path(@post.id), class: :prototype__btn %>
          <%= link_to "削除する", post_path(@post.id), method: :delete, class: :prototype__btn, data: {confirm: "削除しますか？"} %>
        </div>
      <% end %>
      <div class="show_tag"><%= @post.category.name %></div>
      <div class="prototype__image">
        <%= image_tag @post.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__message">
            <%= @post.body %>
          </p>
        </div>
      </div>
      <div class="show-bottom">
        <%# いいね部分始まり %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(@post) %>
            <%= button_to post_like_path(@post), method: :delete,class: :like_btn do %> 
              <div class="like_group">
                <p class= "heart-icon">
                  <i class="fas fa-heart"></i>
                </p>
                <p class="count-number">
                  <%=@post.liked_users.count %>
                </p>
              </div>
            <% end %>
          <% else %> 
            <%= button_to post_likes_path(@post),class: :like_btn do %> 
            <div class="like_group">
                <p class= "heart-icon">
                  <i class="far fa-heart"></i>
                </p>
                <p class="count-number">
                  <%=@post.liked_users.count %>
                </p>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <span class="gray-heart"><i class="fas fa-heart"></i></span>
        <% end %>
        <%# いいね部分終わり %>
        <p class="show-created"><%= l @post.created_at,format: :short %></p>
      </div>

      <%#コメント部分%>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%=form_with model: [@post, @comment], class: :comment_form, local: true do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%="・ #{comment.text}" %>
                <%= link_to comment.user.name, user_path(comment.user_id), class: :comment_user %>
                <p class="comment_created"><%= l comment.created_at,format: :short %></p>

                <%if current_user.id == comment.user.id%>
                  <%= link_to "削除する", post_comment_path(@post, comment),method: :delete, class: :comment_user, data: {confirm: "削除しますか？"} %>
                <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <%#コメント部分終わり%>

    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main"> 
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "● #{@user.name}さんのページ ●"%>
      </h2>

      <div class="post-card">
        <h2 class="list-name">
          <%= "#{@user.name}さんの投稿一覧"%>
        </h2>
        <div class="user__card">
          <%= render partial: "posts/post", collection: @posts %>
        </div>
      </div>

      <div class="like-card">
        <h2 class="list-name">
          <%= "#{@user.name}さんのいいね！一覧"%>
        </h2>
        <div class="user__card">
          <div class="card">          
            <% @user.liked_posts.each do |post| %>
                <p class="tag"><%= post.category.name %></p>
                <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id) %>
                <div class="card__body">
                  <%= link_to post.title, post_path(post.id), class: :card__title%>

                <%# いいね部分始まり %>
                <div class="like_group">
                  <p class= "heart-icon">
                    <i class="fas fa-heart"></i>
                  </p>
                  <p class="post-count-number">
                    <%=post.liked_users.count %>
                  </p>
                </div>
                <%# いいね部分終わり %>
                <div class ="post-bottom">
                  <p class="created"><%= l post.created_at,format: :short %></p>
                  <%= link_to "by #{post.user.name}", user_path(post.user_id), class: :card__user %>
                </div>


            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>